[package]
name = "keep_keeping"
version = "0.1.0"
authors = ["Naqua Darazaki <n.darazaki@gmail.com>"]
edition = "2018"

[dependencies]
walkdir = "2"
filetime = "0.2"
iui = { git = "https://github.com/rust-native-ui/libui-rs.git" }
nfd = "0.0.4"
itertools = "0.8"