[package]
name = "keep-keeping-lib"
version = "0.1.0"
authors = ["Naqua Darazaki <n.darazaki@gmail.com>"]
edition = "2018"

[dependencies]
walkdir = "2"
filetime = "0.2"

[workspace]
members = [
    "cli", "gui"
]