[package]
name = "keep-keeping-gui"
version = "0.1.0"
authors = ["Naqua Darazaki <n.darazaki@gmail.com>"]
edition = "2018"

[dependencies]
keep-keeping-lib = { path = ".." }
iui = { git = "https://github.com/rust-native-ui/libui-rs.git" }
nfd = { version = "0.0.4" }